packages:
  - apps/*
  - packages/*

allowBuilds:
  electron: true
  '@tailwindcss/oxide': true
  esbuild: true
  lefthook: true
  node-pty: true
  unrs-resolver: true

catalog:
  '@tailwindcss/vite': ^4.2.1
  '@types/node': ^24.11.0
  electron: ^40.6.1
  eslint: ^10.0.2
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-unused-imports: ^4.4.1
  lefthook: ^2.1.2
  oxfmt: ^0.36.0
  oxlint: ^1.51.0
  oxlint-tsgolint: ^0.15.0
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  vite: ^7.3.1

minimumReleaseAge: 4320

shellEmulator: true
