packages:
  - apps/*
  - packages/*

allowBuilds:
  "@tailwindcss/oxide": true
  ghostty-web: true
  esbuild: true
  lefthook: true
  unrs-resolver: true

catalog:
  "@tailwindcss/vite": 4.2.1
  "@types/bun": 1.3.10
  "@types/node": 24.12.0
  "@typescript/native-preview": 7.0.0-dev.20260307.1
  electrobun: 1.14.4
  eslint: 10.0.3
  eslint-plugin-import-x: 4.16.1
  eslint-plugin-unused-imports: 4.4.1
  lefthook: 2.1.2
  oxfmt: 0.36.0
  oxlint: 1.51.0
  oxlint-tsgolint: 0.16.0
  tailwindcss: 4.2.1
  typescript: 5.9.3
  vite: 8.0.0-beta.16

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - "@miyaoka/fsss"

shellEmulator: true
