/**
 * vendor/*.json からテーマローダーと名前一覧を生成する。
 * 背景色の luminance で dark/light を判定し、dark → light の順でソートする。
 *
 * 実行: bun packages/themes/scripts/generateThemeLoaders.ts
 */

import fs from "node:fs";
import path from "node:path";

const VENDOR_DIR = path.resolve(import.meta.dir, "../vendor");
const OUTPUT_FILE = path.resolve(import.meta.dir, "../dist/themeLoaders.ts");

/** #RRGGBB → sRGB 相対輝度 */
function luminance(hex: string): number {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
}

interface ThemeEntry {
  name: string;
  file: string;
  isDark: boolean;
}

const LUMINANCE_THRESHOLD = 0.5;

const files = fs.readdirSync(VENDOR_DIR).filter((f) => f.endsWith(".json")).sort();

const themes: ThemeEntry[] = files.map((file) => {
  const json = JSON.parse(fs.readFileSync(path.join(VENDOR_DIR, file), "utf-8")) as {
    background: string;
  };
  const name = file.replace(/\.json$/, "");
  const isDark = luminance(json.background) < LUMINANCE_THRESHOLD;
  return { name, file, isDark };
});

// dark を先、light を後。各グループ内はアルファベット順（files が既にソート済み）
const darkThemes = themes.filter((t) => t.isDark);
const lightThemes = themes.filter((t) => !t.isDark);

const allEntries = [...darkThemes, ...lightThemes];

const loaderEntries = allEntries.map(
  (t) => `  ${JSON.stringify(t.name)}: () => import(${JSON.stringify(`../vendor/${t.file}`)}),`,
);

const content = `// Auto-generated by scripts/generateThemeLoaders.ts — do not edit
export const themeLoaders: Record<string, () => Promise<{ default: unknown }>> = {
${loaderEntries.join("\n")}
};

export const darkThemeNames: string[] = ${JSON.stringify(darkThemes.map((t) => t.name))};
export const lightThemeNames: string[] = ${JSON.stringify(lightThemes.map((t) => t.name))};
export const themeNames: string[] = ${JSON.stringify(allEntries.map((t) => t.name))};
`;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, content);

console.log(
  `Generated ${OUTPUT_FILE}: ${darkThemes.length} dark + ${lightThemes.length} light = ${allEntries.length} themes`,
);
